version: "3"

services:
  localoraichain-a:
    image: local:oraichain
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        RUNNER_IMAGE: alpine:3.19
        GO_VERSION: "1.22"
    volumes:
      - ./scripts/setup_chain.sh:/oraichain/setup.sh
      - $HOME/.oraichaind-local-a/:/oraichain/.oraid/
    entrypoint:
      - /oraichain/setup.sh
    environment:
      - CHAIN_ID=localoraichain-a
      - VALIDATOR_MONIKER=validator-a
      - VALIDATOR_MNEMONIC=family album bird seek tilt color pill danger message abuse manual tent almost ridge boost blast high comic core quantum spoon coconut oyster remove
      - FAUCET_MNEMONIC=increase bread alpha rigid glide amused approve oblige print asset idea enact lawn proof unfold jeans rabbit audit return chuckle valve rather cactus great
      - RELAYER_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
    ports:
      - 26657:26657
      - 1317:1317
      - 9090:9090
    networks:
      - localoraichain

  faucet-a:
    command:
      - start
      - localoraichain-a:26657
    image: confio/faucet:0.28.11
    environment:
      FAUCET_CONCURRENCY: 1
      FAUCET_MNEMONIC: "increase bread alpha rigid glide amused approve oblige print asset idea enact lawn proof unfold jeans rabbit audit return chuckle valve rather cactus great"
      FAUCET_PORT: 8000
      FAUCET_GAS_PRICE: 0.025orai
      FAUCET_PATH_PATTERN: "m/44'/118'/0'/0/a"
      FAUCET_ADDRESS_PREFIX: orai
      FAUCET_TOKENS: orai
      FAUCET_CREDIT_AMOUNT_ORAI: 10000000 # 10 orai
      FAUCET_REFILL_FACTOR: 8
      FAUCET_REFILL_THRESHOLD: 20
      FAUCET_COOLDOWN_TIME: 30 # 30s
    ports:
      - 8000:8000
    depends_on:
      - localoraichain-a
    networks:
      - localoraichain

  localoraichain-b:
    image: local:oraichain
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        RUNNER_IMAGE: alpine:3.19
        GO_VERSION: "1.22"
    volumes:
      - ./scripts/setup_chain.sh:/oraichain/setup.sh
      - $HOME/.oraichaind-local-b/:/oraichain/.oraid/
    entrypoint:
      - /oraichain/setup.sh
    environment:
      - CHAIN_ID=localoraichain-b
      - VALIDATOR_MONIKER=validator-b
      - VALIDATOR_MNEMONIC=family album bird seek tilt color pill danger message abuse manual tent almost ridge boost blast high comic core quantum spoon coconut oyster remove
      - FAUCET_MNEMONIC=increase bread alpha rigid glide amused approve oblige print asset idea enact lawn proof unfold jeans rabbit audit return chuckle valve rather cactus great
      - RELAYER_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
    ports:
      # Can't use the same ports
      - 36657:26657
      - 31317:1317
      - 39090:9090
    networks:
      - localoraichain

  faucet-b:
    command:
      - start
      - localoraichain-b:26657
    image: confio/faucet:0.28.11
    environment:
      FAUCET_CONCURRENCY: 1
      FAUCET_MNEMONIC: "increase bread alpha rigid glide amused approve oblige print asset idea enact lawn proof unfold jeans rabbit audit return chuckle valve rather cactus great"
      FAUCET_PORT: 8000
      FAUCET_GAS_PRICE: 0.025orai
      FAUCET_PATH_PATTERN: "m/44'/118'/0'/0/a"
      FAUCET_ADDRESS_PREFIX: orai
      FAUCET_TOKENS: orai
      FAUCET_CREDIT_AMOUNT_ORAI: 10000000 # 10 orai
      FAUCET_REFILL_FACTOR: 8
      FAUCET_REFILL_THRESHOLD: 20
      FAUCET_COOLDOWN_TIME: 30 # 30s
    ports:
      - 38000:8000
    depends_on:
      - localoraichain-b
    networks:
      - localoraichain

  hermes:
    image: informalsystems/hermes:1.1.0
    user: root:root
    volumes:
      - ./scripts/setup_hermes.sh:/home/hermes/setup.sh
      - ./config/hermes/config.toml:/root/.hermes/config.toml
    entrypoint:
      - /home/hermes/setup.sh
    environment:
      - CHAIN_A_ID=localoraichain-a
      - CHAIN_A_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
      - CHAIN_B_ID=localoraichain-b
      - CHAIN_B_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
    ports:
      - 3000:3000
    depends_on:
      - localoraichain-a
      - localoraichain-b
    networks:
      - localoraichain

networks:
  localoraichain:
